name: "Endid Action"
description: "Call Endid's simple API to notify a Slack channel"
author: "Dan Lester"
inputs:
  token:
    description: "Token for a Slack channel (obtain by typing /endid)"
    required: true
  message:
    description: "Message to include in the Slack notification"
    default: ""
    required: false
outputs:
  response:
    description: "Response from Endid API"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: 'cast'  
  color: 'purple'
  
