name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest

        uses: endid-app/endid-github-action@master

        with:
          token: ${{ secrets.endid_token }}
          message: "From GitHub Actions!"

      - name: Check outputs
        run: |
          test "${{ steps.selftest.outputs.response }}" == "OK"
